version: '3'
services:
  service:
    build: app
    depends_on:
      theatre-db:
        condition: service_healthy
    expose:
      - "8000"
    env_file:
      - ./.env
    volumes:
      - static:/var/www/static
    restart: always


  nginx:
    image: nginx:1.29.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static:/var/www/static:ro
    depends_on:
      - service
    ports:
      - "80:80"
    restart: always

  theatre-db:
    image: postgres:18.0
    env_file:
      - ./.env
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
      - static:/opt/app/static
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always


volumes:
  db-data:
  static:



